close all;
file = csvread('F:\Documents\graduationProject\project\UAV\track2\UAV_offset.csv');
x=file(2:end,2);
y=file(2:end,3);
tt = file(2:end, 1);
offx = file(2:end, 4);
offy = file(2:end, 5);
tx = file(2:end, 6);
ty = file(2:end, 7);
vx = file(2:end, 8);
vy = file(2:end, 9);
init = [-2.5, -2];
plot(x,y,'Linewidth',1.5);
hold on;
load('UAV_traj_variables.mat');
% tx=center(:, 2) + init(1);
% ty=center(:,3) + init(2);
% t1 = center(:, 1);
plot(tx, ty,'Linewidth',1.5);
grid on;
title('Object Tracking With PID Controller');
xlabel('East(m)');
ylabel('North(m)');
figure(2);
plot(tt, x, 'b','Linewidth',1.5);
hold on;
plot(tt, tx, 'r','Linewidth',1.5);
grid on;
title('Time-varying x-trajectory');
xlabel('Time(sec)');
ylabel('x(m)');
legend('UAV', 'Fleet Centroid');
figure(3);
plot(tt, y, 'b','Linewidth',1.5);
hold on;
plot(tt, ty, 'r','Linewidth',1.5);
grid on;
title('Time-varying y-trajectory');
xlabel('Time(sec)');
ylabel('y(m)');
legend('UAV', 'Fleet Centroid');